POST http://localhost:3000/register/visitor
Content-Type: application/json

{
    "username" : "GOH",
    "password" : 111111,
    "_id"      : "000101-02-1111",
    "email"    : "goh@student.utem.edu.my",
    "role"     : "visitor"
}

###
POST http://localhost:3000/register/host
Content-Type: application/json

{
    "username" : "HO",
    "password" : 111111,
    "_id"      : "123456789",
    "email"    : "ho@student.utem.edu.my",
    //"visitor"  : "",
    "role"     : "host"
}

###
POST http://localhost:3000/login
Content-Type: application/json

{
    "username" : "HO",
    "password" : 111111
}

###
POST http://localhost:3000/login/visitor/delete
Content-Type: application/json

{
    "username" : "HO",
    "password" : 111111
}

###
POST http://localhost:3000/login/host/delete
Content-Type: application/json

{
    "username" : "KHOO",
    "password" : 111111
}

###
POST http://localhost:3000/login/host/search
Content-Type: application/json

{
    "_id" : "000101-02-1111"
}

###
POST http://localhost:3000/login/host/addVisitor
Content-Type: application/json

{
    "visitorName" : "GOH",
    "phoneNumber" : "012-3456789",
    "companyName" : "qqqqq",
    "date"        : "2023-06-30"
}

###
POST http://localhost:3000/login/host/removeVisitor
Content-Type: application/json

{
    "visitorName" : "GOH"
}

###
GET http://localhost:3000/login/host/logout

###
GET http://localhost:3000/login/visitor/logout

